### ISSUE TITLE
Visual Studio Community Xamarin - Error with PCL 4.5 project

### ISSUE THREAD

**Issue by livetouchbr** [xamarin/xamarin-macios#6365]
Hi, 

I have a project that was compiling successfully with Visual Studio Community 7.7.3, but after I upgrade to 8.1 (build 2742) it 's not working any more.

This is the compilation error: 
Biometria.cs(14,14): Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?) (CS0234)

More information:
/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2134,5): warning MSB3274: The primary reference "Plugin.Fingerprint, Version=1.4.9.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".

My Xamarin project uses Target Framework: PCL 4.5 - Profile259.

The Fingerprint plugin is compatible with PCL 4.5.

So this error doesn't make any sense. And everything  was working before I update Visual Studio Community. Is it a bug?

I can't send the project because it's private from my client. If you need anything else just le me know.

This is all the information that I have in the About dialog from Visual Studio:
=== Visual Studio Community 2019 for Mac ===

Version 8.1 (build 2742)
Installation UUID: e43806b7-8c53-42b5-959b-9552bf27bc6d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.153 (Visual Studio Community)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin.iOS ===

Version: 12.10.0.153 (Visual Studio Community)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin Designer ===

Version: 16.1.0.464
Hash: 66bb7b43f
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-07 07:10:32 UTC

=== Xamarin.Android ===

Version: 9.3.0.22 (Visual Studio Community)
Commit: HEAD/8e7764fdf
Android SDK: /Users/rlecheta/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@3cb36842fc4
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/rlecheta/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801002742
Git revision: ed27233de1b33083ea2234bc66a3b7824b99bbc7
Build date: 2019-06-12 10:18:51+00
Build branch: release-8.1
Xamarin extensions: 98dc4d7de2257c9b7342dee023910e16d02f8e65

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by dalexsoto** [comment]
Hello!

Thank you for your report, would you be able to send us a small reproducible test case for us to investigate further? Also build logs would be useful.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

Thank you!

**Comment by mrward** [comment]
I do not believe this is specific to Xamarin.iOS. I suspect this may be mono/msbuild related if it worked before.

A simple repro:

1. In Visual Studio for Mac create a Portable Library (PCL) project.
2. Install the Plugin.Fingerprint NuGet package.
3. Change PCL profile to 259 (this is optional - using the default profile 111 also fails)
3. Build the project.

MSBuild outputs warnings similar to:

```
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3274: The primary reference "Plugin.Fingerprint.Abstractions" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3275: The primary reference "Plugin.Fingerprint" could not be resolved because it has an indirect dependency on the assembly "Plugin.Fingerprint.Abstractions, Version=1.4.9.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3274: The primary reference "Plugin.Fingerprint" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".
```

The Plugin.FingerPrint assembly has an assembly attribute of:

`[assembly: TargetFramework (".NETPortable,Version=v5.0", FrameworkDisplayName = ".NET Portable Subset")]`

Going to test out different Mono versions and also see what happens on Windows.

There are two Developer Community posts about this, one that links to here:

 - https://developercommunity.visualstudio.com/content/problem/610984/updated-to-vs-mac-81-mono-5181-now-getting-nuget-t.html
 - https://developercommunity.visualstudio.com/content/problem/613895/my-xamarin-project-doesnt-compile-after-that-last.html

**Comment by mrward** [comment]
This looks to be due to a newer version of MSBuild being more strict with references.

 - Mono 5.18.1.3 - OK
 - Mono 5.18.1.28 - Build warnings
 - Mono 6.0.0.296 - Build warnings

 - VS 2017 on Windows - OK.
 - VS 2019 on Windows - Build warnings.

The warning itself seems to be correct and does not look to be a bug.
The only workarounds would be:
 -  Use older Mono 5.18.1.3
 - Convert the PCL project to a SDK style .NET Standard project

**Comment by dalexsoto** [comment]
Thank you for investigating this @mrward, closing this issue per comment above.

**Comment by livetouchbr** [comment]
I installed a previous version of Mono and it is working.
https://developercommunity.visualstudio.com/content/problem/610984/updated-to-vs-mac-81-mono-5181-now-getting-nuget-t.html
