### ISSUE TITLE
[xcode11] iOS/msbuild test failures

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6325]
http://xamarin-storage/jenkins/xamarin-macios/PR-6305/693c93e20d57481ccc62b1067a730760c60c685b/1/jenkins-results/tests/index.html

```
5) Test Failure : Xamarin.iOS.Tasks.CustomKeyboardTests("iPhone").BasicTest
     #RunTarget-ErrorCount
	The specified task executable "metal" could not be run. System.ComponentModel.Win32Exception (0x80004005): ApplicationName='metal', CommandLine=' -arch air64 -emit-llvm -c -gline-tables-only -ffast-math -serialize-diagnostics obj/iPhone/Debug/metal/Shaders.dia -o obj/iPhone/Debug/metal/Shaders.air -mios-version-min=8.0 Resources/Shaders.metal', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <9f1cacdf07484fa994a9be01060c2bc0>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <9f1cacdf07484fa994a9be01060c2bc0>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at Microsoft.Build.Utilities.ToolTask.ExecuteTool (System.String pathToTool, System.String responseFileCommands, System.String commandLineCommands) [0x000c9] in <786a56000bba4bd3b010933e6ec4e86c>:0 
  at Microsoft.Build.Utilities.ToolTask.Execute () [0x003ad] in <786a56000bba4bd3b010933e6ec4e86c>:0 
  Expected: 0
  But was:  1

6) Test Failure : Xamarin.iOS.Tasks.NativeReferencesNoEmbedding("iPhone").ShouldNotUnnecessarilyRebuildBindingProject(True)
     Binding project build did not create package?
  Expected: True
  But was:  False

7) Test Failure : Xamarin.iOS.Tasks.PhotoEditingTests("iPhone").BasicTest
     #RunTarget-ErrorCount
	expected identifier or '{'
	expected identifier or '{'
	Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
  Expected: 0
  But was:  3
```

Some of these failures only occur when device support is enabled.

6. is related to https://github.com/mono/mono/issues/14876

The other failures in that test run (1-4, 8-9) will be fixed with #6323:

```
Xamarin.iOS.Tasks.CodesignAppBundle("iPhone","Debug").CodesignAfterModifyingWatchApp2Test
     #RunTarget-ErrorCount
	redefinition of 'main'
	Failed to compile the file(s) '/Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/tests/MyWatchKit2IntentsExtension/obj/iPhone/Debug/mtouch-cache/armv7k/main.m'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
```

**Comment by rolfbjarne** [comment]
#6332 fixes 5.

**Comment by rolfbjarne** [comment]
6. will be fixed once we get #6279 in d16-2, then merge d16-2 into xcode11.

**Comment by rolfbjarne** [comment]
6. is fixed in https://github.com/xamarin/xamarin-macios/commit/e9ce1e222aa9da05369eb25029921e3822cfb12a, and that's the last failure.
