### ISSUE TITLE
NWBrowserTest.cs(76,24): error CS0103: The name 'Arch' does not exist in the current context

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#9902]
### Steps to Reproduce

1. Build a PR on `xcode12.2`

### Expected Behavior

Success

### Actual Behavior

xammac_tests fails to build because of https://github.com/xamarin/xamarin-macios/pull/9868

* xammac tests/Mac Modern/Debug: BuildFailure
* xammac tests/Mac Modern/Release: BuildFailure
* xammac tests/Mac Modern/Release: BuildFailure

### Environment

`xcode12.2`

**Comment by spouliot** [comment]
The original PR was merged because it _likely_ did not trigger the execution of `xammac_tests` when the test was was updated.

**Comment by spouliot** [comment]
xammac tests build failures due to https://github.com/xamarin/xamarin-macios/issues/9902

**Comment by spouliot** [comment]
xammac tests build failure due to https://github.com/xamarin/xamarin-macios/issues/9902

**Comment by spouliot** [comment]
https://github.com/xamarin/xamarin-macios/pull/9920 fixed the issue and it did no show up in the latest PR
