### ISSUE TITLE
Some Xamarin.Mac projects fail to compile under XCode 13.2

### ISSUE THREAD

**Issue by MartinRothschink** [xamarin/xamarin-macios#13575]
I have a desktop project based on [Eto.Forms](https://github.com/picoe/Eto) and Xamarin.Mac which targets Framework 4.8. Since update to XCode 13.2 yesterday, the project fails to compile on macOS Monterey 12.1 with XCode 13.2 (13C90).

1. Create a Xamarin.Mac project and target Framework 4.8
2. Compile project with Visual Studio for Mac 2019 stable or Visual Studio for Mac 2022 preview (makes no difference, both fail)

### Expected Behavior
Project compiles successfully

### Actual Behavior
Compile fails with
obj/Osx-Release/mmp-cache/registrar.h(5294,46): error G5B0B056E: 'CXCallObserverDelegate' is unavailable: not available on macOS 
obj/Osx-Release/mmp-cache/registrar.h(5299,42): error GF7055CE9: 'CXProviderDelegate' is unavailable: not available on macOS 

### Environment
macOS Monterey 12.2
XCode 13.2 (13C90)
Visual Studio for Mac 2019 stable, up-to-date
Visual Studio for Mac 2022 preview, up-to-date

### Build Logs
See excerpt above

registrar.m/h contains references to CXCallObserverDelegate and CXProviderDelegate. These files are auto created, so editing won't help. 

Any ideas for a workaround? I need a quick fix/workaround because this is a real showstopper.

Regards
Martin

**Comment by rolfbjarne** [comment]
@MartinRothschink the quick fix you can do yourself is to install the previous version of Xcode (13.1) and use that instead, until we've released a fix on our end.

**Comment by MartinRothschink** [comment]
Thanks, will do.

**Comment by chamons** [comment]
Thanks for the report - Xcode 13.2 support should be released in the near future. 

As noted, downgrading Xcode until then should unbreak you.

**Comment by cwensley** [comment]
I'm running into this too, and downgrading to 13.1 no longer works with macos workload preview 11, as it requires Xcode 13.2.

**Comment by visma-tomi-tavela** [comment]
**Xcode 13.2 / 13.2.1**
Building Xamarin.Forms project with **VS for Mac** works.

Building same  Xamarin.Forms project from **Windows (Visual Studio 2022) using Mac as remote build host**, getting error: 

Error		Couldn't codesign bin/iPhoneSimulator/Debug/XXX/Frameworks/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk/../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator/libswiftCore.dylib: codesign failed with exit code 1			

When downgrading **Xcode to 13.1**, both builds work as expected.

**Comment by mortend** [comment]
I 'm wondering if the fix will be backported to Xamarin.Mac 7.14?

**Comment by rolfbjarne** [comment]
> I 'm wondering if the fix will be backported to Xamarin.Mac 7.14?

No, support for newer versions of Xcode won't be added to older versions of Xamarin.Mac.

**Comment by rolfbjarne** [comment]
Our latest release has support for Xcode 13.2, so I'm closing this now.
