### PR TITLE
Remove PMCS processing of availability attributes

### PR DESCRIPTION
**Pull request by chamons**
- This PR is part of the "remove" PMCS workset, this one focusing on all availability attribute processing.
- As part of the PR involves touching a massive number of files, looking at each individual commit may be useful. In particular "Remove PMCS preprocessing of attributes"
- This PR is _IN WORK_. It commits, but let's not ship it yet.

### CODE REVIEW

File: src/appkit.cs [hunk 1]
```diff
@@ -7991,7 +7991,7 @@ interface NSMenuItemCell {
 
 	}
 
-	[Availability (Introduced = Platform.Mac_10_0 | Platform.Mac_Arch32)]
+	[IntroducedAttribute (PlatformName.MacOSX, 10, 0, PlatformArchitecture.Arch32)]
```
Comment (spouliot) [inline src/appkit.cs]: minor: we can drop the `Attribute` suffix

File: src/WKWebKit/Defs.cs [hunk 2]
```diff
@@ -101,7 +106,7 @@ public enum WKDataDetectorTypes : nuint {
 #endif
 	}
 
-	[iOS (10,0)][Mac (10,12, only64: true)]
+	[iOS (10,0)][Mac (10,12, onlyOn64: true)]
```
Comment (spouliot) [inline src/WKWebKit/Defs.cs]: how did that compile ? :|

File: src/qtkit.cs [hunk 3]
```diff
@@ -262,7 +262,8 @@ interface QTCaptureDevice : NSCoding {
 		[Field ("QTCaptureDeviceInputSourceLocalizedDisplayNameKey")]
 		NSString InputSourceLocalizedDisplayNameKey { get; }
 		
-		[Availability (Introduced = Platform.Mac_10_5 | Platform.Mac_Arch32)]
+		[IntroducedAttribute (PlatformName.MacOSX, 10, 5, PlatformArchitecture.Arch32)] 
+		[DeprecatedAttribute (PlatformName.MacOSX, 10, 9)]
```
Comment (spouliot) [inline src/qtkit.cs]: where does the deprecated comes from ?

File: src/qtkit.cs [hunk 4]
```diff
@@ -614,17 +615,20 @@ interface QTFormatDescription {
 
 	[BaseType (typeof (NSObject))]
 	interface QTMedia {
-		[Availability (Introduced = Platform.Mac_10_3 | Platform.Mac_Arch32, Deprecated = Platform.Mac_10_9)]
+		[IntroducedAttribute (PlatformName.MacOSX, 10, 3, PlatformArchitecture.Arch32)] 
+		[DeprecatedAttribute (PlatformName.MacOSX, 10, 5)]
```
Comment (spouliot) [inline src/qtkit.cs]: mismatch, deprecated was 10.9 and now is 10.5

File: src/scenekit.cs [hunk 5]
```diff
@@ -2398,7 +2398,8 @@ interface SCNRenderer : SCNSceneRenderer, SCNTechniqueSupport {
 
 		[NoWatch, NoTV]
 		[Export ("render")]
-		[Availability (Deprecated = Platform.Mac_10_11 | Platform.iOS_9_0)]
+		[Availability (Deprecated = Platform.Mac_10_11)]
+		[Availability (Deprecated = Platform.iOS_9_0)]
```
Comment (spouliot) [inline src/scenekit.cs]: maybe it would be best, when replacing, to use the latest attribute ? i.e.
`[Deprecated (PlatformName.iOS, 9, 0)]`

File: src/WKWebKit/Defs.cs (hunk 2 above)
Comment (chamons) [reply src/WKWebKit/Defs.cs]: PMCS "fixed" it before it hit a compiler.

File: src/scenekit.cs (hunk 5 above)
Comment (chamons) [reply src/scenekit.cs]: For sure. It just involves more than 20 minutes and 5 vim macros to bang that out.

If you think it's worth it, I can hack this out (in a new PR).

File: src/qtkit.cs (hunk 4 above)
Comment (chamons) [reply src/qtkit.cs]: I copy pasted a few of these before writing up macros, and I apparently screwed a few up...

File: src/WKWebKit/Defs.cs (hunk 2 above)
Comment (spouliot) [reply src/WKWebKit/Defs.cs]: :lol:

File: src/scenekit.cs (hunk 5 above)
Comment (spouliot) [reply src/scenekit.cs]: yeah, let's split this out in a few different PR, starting the the old, named attributes
and we can split the work across the remaining people not yet on vacation :)

File: src/generator-attribute-manager.cs [hunk 6]
```diff
@@ -83,8 +85,56 @@ static Type ConvertType (System.Type type, ICustomAttributeProvider provider)
...
+		case "ObjCRuntime.Extensions":
+			break;
+		default:
+			return Enumerable.Empty<System.Attribute> ();
+		}
+
+		switch (attribute.AttributeType.Name) {
+		case "SinceAttribute":
+		case "iOSAttribute":
+			return AttributeConversionManager.ConvertPlatformAttribute (attribute, 2 /* PlatformName.iOS */).Yield ();
```
Comment (timrisi) [inline src/generator-attribute-manager.cs]: Would it be better to cast these from the PlatformName enums instead of hard-coding the numbers, simply to make it harder to accidentally put in the wrong value if changes need to be made in the future? (And so one wouldn't have to look up what values they need to use from the enum if they have to make changes).

File: src/generator-attribute-manager.cs [hunk 7]
```diff
@@ -269,3 +322,261 @@ static bool IsSubclassOf (Type base_class, Type derived_class)
...
+	{
+		return CreateMajorMinorAttribute (ObsoletedAttributeType, platform, major, minor, arch, message);
+	}
+
+	public static System.Attribute CreateDeprecatedAttribute (PlatformName platform, int major, int minor, byte arch = 0xff, string message = "")
+	{
+		return CreateMajorMinorAttribute (DeprecatedAttributeType, platform, major, minor, arch, message);
+	}
+
+	public static System.Attribute CreateUnavilableAttribute (PlatformName platformName, byte arch = 0xff, string message = "")
```
Comment (timrisi) [inline src/generator-attribute-manager.cs]: This is the original misspelled method for Sebastian's comment about misspelled Unavailable

File: src/ObjCRuntime/PlatformAvailability2.cs [hunk 8]
```diff
@@ -205,4 +205,249 @@ public sealed class UnavailableAttribute : AvailabilityBaseAttribute
...
+		Mac_10_6  =   0x1000000000060000,
+		Mac_10_7  =   0x1000000000070000,
+		Mac_10_8  =   0x1000000000080000,
+		Mac_10_9  =   0x1000000000090000,
+		Mac_10_10 =   0x10000000000a0000,
+		Mac_10_10_3 = 0x10000000000a0300,
+		Mac_10_11   = 0x10000000000b0000,
+		Mac_10_11_3 = 0x10000000000b0300,
+		Mac_10_12   = 0x10000000000c0000,
+		Mac_10_13   = 0x10000000000d0000,
```
Comment (timrisi) [inline src/ObjCRuntime/PlatformAvailability2.cs]: No tags needed for the other subversions (10.1, 10.2, 11.1, 11.2, anything for 10.12.x or 10.13.x)?

**Comment by timrisi** [comment]
Also helps if I remember I'm reviewing the original commit when I make comments so I don't review on stuff that's already done 😇

**Comment by chamons** [comment]
I rewrote the conversion code to simplify it and add cases for PlatformArch that will be introduced in https://github.com/xamarin/xamarin-macios/pull/3101.

I also reverted the 2nd and 3rd commit, since they will be covered by that, going first.

This is thus dont-merge until at least it lands and is resolved/tested.

**Comment by chamons** [comment]
Still looking into if I can remove the using hacks but unsure it'll get better...

**Comment by chamons** [comment]
As I reverted the conversion bits now covered in https://github.com/xamarin/xamarin-macios/pull/3101 it will fail to build until that lands. This is expected.

**Comment by spouliot** [comment]
Last commit produced a few errors -> ```21:54:04 /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/src/gamekit.cs(1163,79): error CS1016: Named attribute arguments must appear after the positional arguments
```

**Comment by chamons** [comment]
@spouliot https://github.com/xamarin/xamarin-macios/pull/3096#issuecomment-352830355

**Comment by chamons** [comment]
Depends on this PRs landing first:

https://github.com/xamarin/xamarin-macios/pull/3125
https://github.com/xamarin/xamarin-macios/pull/3123

Else it won't build.

Locally I was able to run the non-bcl mac tests successfully with those applied.

File: src/generator-attribute-manager.cs [hunk 9]
```diff
@@ -170,12 +220,15 @@ static System.Attribute CreateAttributeInstance (CustomAttributeData attribute,
 		List<T> list = null;
 		for (int i = 0; i < attributes.Count; i++) {
 			var attrib = attributes [i];
-			if (attrib.AttributeType != type && !IsSubclassOf (type, attrib.AttributeType))
-				continue;
 
-			if (list == null)
-				list = new List<T> ();
-			list.Add ((T) CreateAttributeInstance (attributes [i], provider));
+			foreach (var newAttribute in CreateAttributeInstance (attributes [i], provider)) {
```
[the remark this answers is not in the document]
Comment (chamons) [reply src/generator-attribute-manager.cs]: Doesn't that shadow the variable on 172?

File: src/generator-attribute-manager.cs [hunk 10]
```diff
@@ -269,3 +322,261 @@ static bool IsSubclassOf (Type base_class, Type derived_class)
...
+	public static System.Type IntroducedAttributeType = typeof (TypeManager).Assembly.GetType ("XamCore.ObjCRuntime.IntroducedAttribute");
+	public static System.Type UnavailableAttributeType = typeof (TypeManager).Assembly.GetType ("XamCore.ObjCRuntime.UnavailableAttribute");
+	public static System.Type ObsoletedAttributeType = typeof (TypeManager).Assembly.GetType ("XamCore.ObjCRuntime.ObsoletedAttribute");
+	public static System.Type DeprecatedAttributeType = typeof (TypeManager).Assembly.GetType ("XamCore.ObjCRuntime.DeprecatedAttribute");
+
+	public static System.Attribute CreateNewAttribute (System.Type attribType, System.Type [] ctorTypes, object [] ctorValues)
+	{
+		var ctor = attribType.GetConstructor (ctorTypes);
+		if (ctor == null)
+			throw ErrorHelper.CreateError (1058, "Internal error: could not find a constructor for the mock attribute '{0}'. Please file a bug report (https://bugzilla.xamarin.com) with a test case.", attribType.FullName);
```
[the remark this answers is not in the document]
Comment (chamons) [reply src/generator-attribute-manager.cs]: I stole it from here:

https://github.com/xamarin/xamarin-macios/blob/master/src/generator-attribute-manager.cs#L133

and we have a bunch of these to update:

```
gg "file a bug report" | grep -v docs | wc -l
     131
```

So I'd rather someone did it in an unrelated PR.

**Comment by chamons** [comment]
With both of the prereq PRs landing, this might actually build/run tests 🎉 finally.

File: src/generator-attribute-manager.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (VincentDondain) [reply src/generator-attribute-manager.cs]: I'm just wondering why you're not using the variable that was already created here, that's all (:

[the remark this answers is not in the document]
Comment (chamons) [reply src/generator-attribute-manager.cs]: I'm taking that existing attribute, feeding it into CreateAttributeInstance which may convert it into one or more new attributes and adding those.

Shadowing the existing variable seems strange. I could remove attrib, have the two locations do attributes[i] and use it I guess...

File: tests/introspection/ApiTypoTest.cs [hunk 11]
```diff
@@ -323,6 +323,7 @@ protected ApiTypoTest ()
 			"Ntsc",
 			"nuint",
 			"Ndef",
+			"Noi", // From NoiOSAttribute
```
Comment (spouliot) [inline tests/introspection/ApiTypoTest.cs]: hmm... that was not caught before because it was turned into a `[Unavailable]` right ?

Comment (chamons) [reply tests/introspection/ApiTypoTest.cs]: Correct. But I added [NoiOS] and friends to match the [Mac] and friends that derive from the right attribute (since we're having to change tooling, let's make all of the common shortcuts work).

Comment (chamons) [reply tests/introspection/ApiTypoTest.cs]: https://github.com/xamarin/xamarin-macios/pull/3096/files#diff-8f0ef92138e06cd064a011ea8aad8d8bR279

**Comment by spouliot** [comment]
The xtro failures is because the PR adds (non public) types that have no namespaces (it's a required hack). I'll fix this (in xtro) in a separate PR. There's nothing else (from xtro) blocking this PR (it can be considered green).

File: src/ObjCRuntime/PlatformAvailability2.cs [hunk 12]
```diff
@@ -205,4 +205,83 @@ public sealed class UnavailableAttribute : AvailabilityBaseAttribute
...
 	}
+
+	public sealed class TVAttribute : IntroducedAttribute
+	{
+		public TVAttribute (byte major, byte minor)
+			: base (PlatformName.TvOS, (int)major, (int)minor)
+		{
+		}
+
+		public TVAttribute (byte major, byte minor, bool onlyOn64 = false)
```
Comment (marek-safar) [inline src/ObjCRuntime/PlatformAvailability2.cs]: What's the point of default onlyOn64 parameter `false` value ? I cannot think of case where it will be used

Comment (chamons) [reply src/ObjCRuntime/PlatformAvailability2.cs]: I just copy pasted the existing API from PlatformAvailability.cs to keep the API. I could have searched for usage and removed some but:

- I'd also have to search all branches in flight, such as any release/xcode not merged to master
- You lose some symmetry if you can do [Mac (10, 12, onlyOn64 : true) but not [TV (11, 0, onlyOn64 : true)]

Comment (marek-safar) [reply src/ObjCRuntime/PlatformAvailability2.cs]: My comment is not about API but about default false value for onlyOn64, why is it there?

Comment (chamons) [reply src/ObjCRuntime/PlatformAvailability2.cs]: I'm not sure what you are asking. 

Technically we are matching the original platform availability API found here:

https://github.com/xamarin/xamarin-macios/blob/master/src/ObjCRuntime/PlatformAvailability.cs#L593

In general, we have that override to allow us to mark certain APIs as 64-bit only as Apple often loves to either remove 32-bit implementations or never provide them.

If you are asking why we have it = false when that gives it the same behavior as above we want:

[TV (11, 0)] to not be 64-bit only and if it was = true we'd get that. The common pattern is [TV (11, 0, onlyOn64 : true)] to make it more clear in bindings what the true is for.

Looking at it, we maybe could have collapsed it to one ctor with more default parameters like

(byte major, byte minor, byte point = 0, bool onlyOn64 = false)

But I was looking to match the old API as close as possible.

Also, the reason that we never needed this was that these were processed by PMCS and converted into other attributes before the compiler ever saw them (see deleted code).

Comment (marek-safar) [reply src/ObjCRuntime/PlatformAvailability2.cs]: > If you are asking why we have it = false when that gives it the same behavior as above we want:

Yes as `[TV (11, 0)]` won't use this overload, the only way to use it is to use explicit parameter name but then the default value won't be used

Comment (rolfbjarne) [reply src/ObjCRuntime/PlatformAvailability2.cs]: tvOS is always 64-bits, so the `onlyOn64` parameter is redundant for tvOS.

The opposite logic goes for watchOS (it's always 32-bits), but I guess that can change in the future, so the parameter is fine.
