### ISSUE TITLE
[.net6-ios] Binding project fails to compile when multiple <RuntimeIdentifiers> are specified in csproj file

### ISSUE THREAD

**Issue by adydecki** [xamarin/xamarin-macios#15373]
### Steps to Reproduce

1. Create .net6-ios binding project with a xcframework as the native framework reference `dotnet new iosbinding -n iOSBinding`
2. Add following RIDs for iOS in .csproj file `<RuntimeIdentifiers>ios-arm64;ios-x64;ios-x86</RuntimeIdentifiers>`
3. Build the iOS binding project

### Expected Behavior
The project builds successfully for each runtime identifier.

### Actual Behavior
The compilation error shows up `error MSB4044: The "CompileAppManifest" task was not given a value for the required parameter "AppBundleName".`

Please note the error does not occur when `<RuntimeIdentifiers>` is removed from the csproj file and each runtime identifier is built separately, e.g. `dotnet build -r ios-arm64 --self-contained`, `dotnet build -r ios-x64 --selft-contained`, etc. 

### Environment

```Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 1038)
Installation UUID: 9a5d47a6-93b4-4f63-9939-28dc7ea9b0fa

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-2.22307.14+b91fc5b06135deb5bd72c105a1b96ce278ad6beb

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.301/Sdks
SDK Versions:
	6.0.301
	6.0.300
	6.0.203
	6.0.202
	6.0.201
	6.0.200
	6.0.106
	6.0.105
	6.0.102
	6.0.101
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.201
	5.0.103
	5.0.102
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.407
	3.1.406
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.4
	5.0.3
	5.0.2
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.13
	3.1.12
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.3.0.110
Hash: 01d90a6c4
Branch: remotes/origin/d17-3
Build date: 2022-06-17 20:21:53 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin.Android
Version: 12.2.8.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/adrian/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0  (API level 26)
		6.0  (API level 23)
		12.0 (API level 31)
		4.4  (API level 19)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		7.0  (API level 24)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.47
Hash: d6dd135
Branch: remotes/origin/dev/tondat/main-menues~3
Build date: 2022-06-17 20:21:57 UTC

Android Device Manager
Version: 0.0.0.1127
Hash: 4bb4d48
Branch: remotes/origin/dev/tondat/main-1536295~1
Build date: 2022-06-17 20:21:57 UTC

Build Information
Release ID: 1703001038
Git revision: ab015cef741e20e3cc212648659ecbd4ed089d5a
Build date: 2022-06-17 20:19:58+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9010082/msbuild.binlog.zip)

### Example Project (If Possible)

The example project can be found at https://github.com/adydecki/net6-maui-test/tree/main/iOSBindingLib

**Comment by adydecki** [comment]
Follow up question I have is do I need all of the `ios-arm64;ios-x64;ios-x86` runtime identifiers in the binding iOS project? Or is it enough to build the binding project without specifying any of the runtime identifiers? In such a case will I be able to run the code in simulator and on the device?

**Comment by rolfbjarne** [comment]
> do I need all of the ios-arm64;ios-x64;ios-x86 runtime identifiers in the binding iOS project? Or is it enough to build the binding project without specifying any of the runtime identifiers?

There's no need to specify runtime identifiers for binding (or class library) projects, and as you've found out it doesn't work anyways.

> In such a case will I be able to run the code in simulator and on the device?

Yes, assuming the native library you've bound contains native code for all the platforms you want to target.

**Comment by adydecki** [comment]
Thank you for your quick answer. I removed all RIDs from the binding project and created a NuGet package where I placed the binding binaries output into `lib\net6.0-ios11.0\iOSBinding.dll` along with the native references which are placed as `content\iOSBinding.resources` and when using that NuGet package in the .net6-ios app which I want to publish via command `dotnet publish -r ios-arm64 --self-contained` I get the build error as follows:
```
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/6.0.4/Sdk/../tools/mono-aot-cross execution finished (exit code = 1).
 
Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/6.0.4/Sdk/../tools/mono-aot-cross execution finished (exit code = 1).

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.2.302-preview.14.122/targets/Xamarin.Shared.Sdk.targets(977,3): error : Failed to AOT compile BarcodeSelectionSimpleSample.dll, the AOT compiler exited with code 1
```
If I do not provide the `-r ios-arm64` during the application publish I get 
```
error : A runtime identifier must be specified in order to publish this project.
```

The above does not occur when I build the binding project with `-r ios-arm64` specified and place it in the NuGet package under `runtimes\ios-arm64\lib\net6.0-ios11.0\iOSBinding.dll`

**Comment by adydecki** [comment]
Something wrong was on my side most likely with some stale/cached previous NuGet packages. When I run `nuget locals all -clear` and did the application publish again the error did not show up. Again thanks for the quick answer.
