### PR TITLE
[xtro] Report missing-protocol-conformance when protocols are defined…

### PR DESCRIPTION
**Pull request by VincentDondain**
… in categories

- Fixes bug #59272: [xtro] Report !missing-protocol-conformance! when protocols are defined in categories
(https://bugzilla.xamarin.com/show_bug.cgi?id=59272)
- Implemented missing protocol conformances based on tool's new data.

### CODE REVIEW

**Comment by VincentDondain** [comment]
Damn I thought I fixed: `[FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder:`. Investigating.

File: src/gamekit.cs [hunk 1]
```diff
@@ -696,7 +696,11 @@ interface GKLeaderboardViewController : UIAppearance
 	[Watch (3,0)]
 	[Mac (10, 8)]
 	[BaseType (typeof (GKPlayer))]
-	interface GKLocalPlayer {
+	interface GKLocalPlayer
+#if !TVOS && !WATCH
+	: GKSavedGameListener
+#endif
```
Comment (spouliot) [inline src/gamekit.cs]: that's something that should be fixed

File: tests/xtro-sharpie/iOS-QuickLook.ignore [hunk 2]
```diff
@@ -1,2 +1,5 @@
 ## fixed for XAMCORE_4_0
 !incorrect-protocol-member! QLPreviewItem::previewItemTitle is OPTIONAL and should NOT be abstract
+
+## Getting "[FAIL] Selector not found for Foundation.NSUrl : previewItemTitle" when NSUrl conforms to 'QLPreviewItem'
+!missing-protocol-conformance! NSURL should conform to QLPreviewItem (defined in 'QLPreviewConvenienceAdditions' category)
```
Comment (spouliot) [inline tests/xtro-sharpie/iOS-QuickLook.ignore]: That's probably because of the entry just above - if it's `optional` then having it not responding is _normal_

File: src/avfoundation.cs [hunk 3]
```diff
@@ -11513,24 +11509,21 @@ interface AVSampleBufferDisplayLayer {
...
-
-		[Export ("enqueueSampleBuffer:")]
+#if !XAMCORE_4_0
+		[Wrap ("Enqueue (sampleBuffer)", IsVirtual = true)]
+		[Obsolete ("Use the 'Enqueue' method instead.")]
 		void EnqueueSampleBuffer (CMSampleBuffer sampleBuffer);
-
-		[Export ("flush")]
-		void Flush ();
+#endif
```
[the remark this answers is not in the document]
Comment (VincentDondain) [reply src/avfoundation.cs]: Conflict it is (:

File: src/avfoundation.cs [hunk 4]
```diff
@@ -11513,24 +11509,21 @@ interface AVSampleBufferDisplayLayer {
...
 
 		[Export ("flushAndRemoveImage")]
 		void FlushAndRemoveImage ();
 
-		[Export ("requestMediaDataWhenReadyOnQueue:usingBlock:")]
+#if !XAMCORE_4_0
+		[Wrap ("RequestMediaData (queue, enqueuer)", IsVirtual = true)]
+		[Obsolete ("Use the 'RequestMediaData' method instead.")]
 		void RequestMediaDataWhenReadyOnQueue (DispatchQueue queue, Action enqueuer);
+#endif
```
[the remark this answers is not in the document]
Comment (VincentDondain) [reply src/avfoundation.cs]: same ;)

File: src/foundation.cs [hunk 5]
```diff
@@ -3542,7 +3551,7 @@ interface NSDate : NSSecureCoding, NSCopying {
 	}
 	
 	[BaseType (typeof (NSObject))]
-	interface NSDictionary : NSSecureCoding, NSMutableCopying {
+	interface NSDictionary : NSSecureCoding, NSMutableCopying, NSFetchRequestResult, INSFastEnumeration {
```
[the remark this answers is not in the document]
Comment (VincentDondain) [reply src/foundation.cs]: Yup I saw that: https://bugzilla.xamarin.com/buglist.cgi?classification=Xamarin&f1=target_milestone&f2=bug_status&f3=bug_status&list_id=333166&o1=equals&o2=notequals&o3=notequals&product=iOS&query_format=advanced&v1=15.6&v2=RESOLVED&v3=VERIFIED

But `INSFastEnumeration` has a message saying: "Placeholer, just so we can start flagging things" and `NSArray` is already using `INSFastEnumeration` so I figured it was valid to add it to `NSDictionary`. 

I already added it to the .ignore file: https://github.com/xamarin/xamarin-macios/pull/3187/files#diff-e909b6d483a4c2c9cbff0a2076e1406aR889

File: tests/introspection/ApiProtocolTest.cs [hunk 6]
```diff
@@ -184,6 +184,9 @@ protected virtual bool Skip (Type type, string protocolName)
 					return true;
 				}
 				break;
+			// Undocumented conformance (members were inlinded in 'UIViewController' before so all subtypes should conform)
+			case "UIStateRestoring":
+				return true;
```
[the remark this answers is not in the document]
Comment (VincentDondain) [reply tests/introspection/ApiProtocolTest.cs]: Put skipping `UIViewController` doesn't skip all the subtypes and if I manually add all the subtypes (20 or 30) it'll fail whenever we add a new subtype (hence the super general condition :/ )

File: src/foundation.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (spouliot) [reply src/foundation.cs]: not sure your first link is related - bad copy/paste ?

File: tests/introspection/ApiProtocolTest.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (spouliot) [reply tests/introspection/ApiProtocolTest.cs]: You have `Type type` so you should be able to check for subclasses - which, I agree, would be better than adding 20-30 more entries

File: tests/xtro-sharpie/ObjCInterfaceCheck.cs [hunk 7]
```diff
@@ -60,6 +62,40 @@ public override void VisitManagedType (TypeDefinition type)
...
+		{
+			if (visitKind != VisitKind.Enter)
+				return;
+
+			var categoryName = decl.Name;
+			if (categoryName == null)
+				return;
+
+			if (categoryName.EndsWith ("Internal", StringComparison.Ordinal))
+				return;
```
[the remark this answers is not in the document]
Comment (VincentDondain) [reply tests/xtro-sharpie/ObjCInterfaceCheck.cs]: Sure but then that comment also applies to https://github.com/xamarin/xamarin-macios/blob/master/tests/xtro-sharpie/ObjCInterfaceCheck.cs#L70-L72 right?

[the remark this answers is not in the document]
Comment (spouliot) [reply tests/xtro-sharpie/ObjCInterfaceCheck.cs]: yes, I thought they were all removed

File: src/foundation.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (VincentDondain) [reply src/foundation.cs]: Oops, updated.

**Comment by spouliot** [comment]
Something looks 🐟 with `NSString` in API diff, several properties/methods are being added as `virtual` but they should already exists in `NSObject` (so at best it would be `override`).

File: src/foundation.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (rolfbjarne) [reply src/foundation.cs]: Yes, please add `INSFastEnumeration` when applicable, that way we'll automatically get it when it's implemented.

**Comment by VincentDondain** [comment]
@spouliot here's the [diff](https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c) from the generator. Everything other than NSString.g.cs looks fine (expected based on the code changes).

File: src/mapkit.cs [hunk 8]
```diff
@@ -280,11 +280,14 @@ interface MKDirectionsRequest {
 	[TV (9,2)]
 	[Mac (10,9, onlyOn64 : true)]
 	interface MKMapItem
-#if !MONOMAC
-		: NSSecureCoding
 #if IOS // #if TARGET_OS_IOS
-		, NSItemProviderReading, NSItemProviderWriting
+		: NSItemProviderReading, NSItemProviderWriting
+#if ARCH_64 // [FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder: on 32-bit iOS
+		, NSSecureCoding
```
Comment (spouliot) [inline src/mapkit.cs]: We can't do that in public API, e.g. if 32bits and 64bits signatures are different then this _leaks_ into user code
It also becomes impossible (or at least harder) to de-duplicate the platform assemblies (for fat apps)

This needs to be considered a OS version change (which it is) e.g. when a new version of iOS adds conformance then we add the API (and fix up introspection not to report it for older versions)

File: src/mapkit.cs [hunk 9]
```diff
@@ -280,11 +280,14 @@ interface MKDirectionsRequest {
...
 #endif
+#endif
+#if WATCH || TVOS || MONOMAC && ARCH_64
+		: NSSecureCoding
```
Comment (spouliot) [inline src/mapkit.cs]: same

File: tests/xtro-sharpie/iOS-MapKit.ignore [hunk 10]
```diff
@@ -9,3 +9,6 @@
 !missing-field! MKAnnotationCalloutInfoDidChangeNotification not bound
 !missing-protocol-conformance! MKUserLocation should conform to MKAnnotation
 !missing-protocol-member! MKOverlay::coordinate not found
+
+## Getting "[FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder:" when 'MKMapItem' implements 'NSSecureCoding' on 32-bit iOS
+!missing-protocol-conformance! MKMapItem should conform to NSSecureCoding (defined in 'MKMapItemSerialization' category)
```
Comment (spouliot) [inline tests/xtro-sharpie/iOS-MapKit.ignore]: looks like the previous case, it must be handled like a version change (not an arch specific change)
keep it mind xtro uses the 64bits .pch (from sharpie) to applies the rules

File: tests/xtro-sharpie/macOS-MapKit.ignore [hunk 11]
```diff
@@ -6,5 +6,5 @@
 !unknown-native-enum! MKFeatureVisibility bound
 !unknown-native-enum! MKUserTrackingMode bound
 
-## Getting "[FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder:" when 'MKMapItem' implements 'NSSecureCoding' on macOS
+## Getting "[FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder:" when 'MKMapItem' implements 'NSSecureCoding' on 32-bit macOS
```
Comment (spouliot) [inline tests/xtro-sharpie/macOS-MapKit.ignore]: same (it's also using 64bits .pch for macOS)

File: tests/introspection/iOS/iOSApiProtocolTest.cs [hunk 12]
```diff
@@ -681,6 +681,10 @@ protected override bool Skip (Type type, string protocolName)
 
 			case "UIPasteConfigurationSupporting": // types do not conform to protocol but protocol methods work on those types (base type tests in monotouch-test)
 				return true; // Skip everything because 'UIResponder' implements 'UIPasteConfigurationSupporting' and that's 130+ types
+
+			// Undocumented conformance (members were inlinded in 'UIViewController' before so all subtypes should conform)
+			case "UIStateRestoring":
+				return type.Name == "UIViewController" || type.IsSubclassOf (typeof (UIViewController));
```
Comment (spouliot) [inline tests/introspection/iOS/iOSApiProtocolTest.cs]: 👍

File: tests/xtro-sharpie/iOS-MapKit.ignore (hunk 10 above)
Comment (spouliot) [reply tests/xtro-sharpie/iOS-MapKit.ignore]: oops, I reviewed the individual commits and some comments are not showing, see the _previous_ in https://github.com/xamarin/xamarin-macios/pull/3187/commits/0f00cb1e1424ff4665069b433c673bf27e16975c

**Comment by spouliot** [comment]
@VincentDondain there's a small problem with https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c
and it does show why (at least some) delegates where not inlined.

`AVQueuedSampleBufferRendering` (iOS 11) was added after `AVSampleBufferDisplayLayer` (iOS 8) so members, like `Enqueue` are now shown to require iOS11 (which is not true). Same for `AVSampleBufferDisplayLayer`

`UIViewController` also has a similar issue with `DecodeRestorableState` and `EncodeRestorableState`

There are also an extra (generated, the one I mentioned before were after the final compilation) `new` https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c#file-diff-L228 https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c#file-diff-L883

note: I only looked at iOS (not others platforms) so there might be a few more.

We might need to split the commit (a few things, like availability, likely requires a generator changes) to get merge most of it _soonish_

File: src/mapkit.cs (hunk 8 above)
Comment (rolfbjarne) [reply src/mapkit.cs]: My guess is that it's actually tied to the OS version (it works in iOS 11 (64-bit only), but not iOS 10.3 (where we run our 32-bit tests))

**Comment by VincentDondain** [comment]
@spouliot not sure what's "breaking" when adding a new interface to an existing protocol (the new protocol I'm adding is empty on tvOS). It's not like I'm adding a member ([doc](https://github.com/xamarin/xamarin-macios/wiki/BINDINGS#protocols-breaking-changes)).

See https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5929/API_diff

Also no idea why MetalPerformanceShaders breaking changes are raised (does not happen locally).

File: src/mapkit.cs (hunk 8 above)
Comment (VincentDondain) [reply src/mapkit.cs]: That explains why I couldn't find many `ARCH_64`, thought I was being clever here :P

But yes I now remember how we usually handle `NSSecureCoding`, I got distracted.

**Comment by spouliot** [comment]
@VincentDondain sorry, too many comments :) I need context for _not sure what's "breaking" when adding a new interface to an existing protocol (the new protocol I'm adding is empty on tvOS_

**Comment by VincentDondain** [comment]
@spouliot about the breaking change that shows up on the tvOS API diff (link above).

```
Namespace GameKit

Type Changed: GameKit.IGKLocalPlayerListener

Added interface:

	IGKSavedGameListener
```

GKLocalPlayerListener.g.cs show:

```
public interface IGKLocalPlayerListener : INativeObject, IDisposable, 
		GameKit.IGKChallengeListener
		, GameKit.IGKInviteEventListener
		, GameKit.IGKSavedGameListener
		, GameKit.IGKTurnBasedEventListener
		
{
}
```

and

```
public unsafe partial class GKLocalPlayerListener : NSObject, IGKLocalPlayerListener, IGKChallengeListener, IGKInviteEventListener, IGKSavedGameListener, IGKTurnBasedEventListener {
(...)
```

Why is adding a new interface a breaking change? It's different from adding a new [*required* member to an existing protocol](https://github.com/xamarin/xamarin-macios/wiki/BINDINGS#protocols-breaking-changes).

**Comment by spouliot** [comment]
@VincentDondain oh, that's one we have to _tolerate_. It's not a problem with the protocol, but with .net.

E.g. If you have an existing binary `A.dll` with a type that implements `IGKLocalPlayerListener` and then update to the new XI+1 then this type becomes invalid (because the type does not implement all the interface members). 

It's one of place where the (upcoming) default interface methods will help us.

File: tests/xtro-sharpie/iOS-MapKit.ignore [hunk 13]
```diff
@@ -8,7 +8,4 @@
 
 !missing-field! MKAnnotationCalloutInfoDidChangeNotification not bound
 !missing-protocol-conformance! MKUserLocation should conform to MKAnnotation
-!missing-protocol-member! MKOverlay::coordinate not found
-
-## Getting "[FAIL] Selector not found for MapKit.MKMapItem : encodeWithCoder:" when 'MKMapItem' implements 'NSSecureCoding' on 32-bit iOS
-!missing-protocol-conformance! MKMapItem should conform to NSSecureCoding (defined in 'MKMapItemSerialization' category)
\ No newline at end of file
+!missing-protocol-member! MKOverlay::coordinate not found
```
Comment (rolfbjarne) [inline tests/xtro-sharpie/iOS-MapKit.ignore]: For the future: make sure to end files with a newline to avoid diff noise :smile:

Comment (rolfbjarne) [reply tests/xtro-sharpie/iOS-MapKit.ignore]: And I should stop commenting until I've read all the commits...

**Comment by VincentDondain** [comment]
> this type becomes invalid (because the type does not implement all the interface members)

@spouliot but in the case of this PR, there are no new interface members since `IGKSavedGameListener` is empty. So `IGKLocalPlayerListener` still implements all the interface members...

Also what did you mean by: "that's one we have to tolerate" ignore the API diff? Special case?

**Comment by spouliot** [comment]
@VincentDondain api-diff is not that smart :) it's also a bad practice (in .net) to use empty interface (it's better to use attributes). Of course since ours are mapped to protocols we must add them (even if empty).

The tolerance is for the case I mentioned before. We cannot stop adding new protocols even if, in some case, they could break things (we take more care for members).

**Comment by VincentDondain** [comment]
New generated code diff: https://gist.github.com/VincentDondain/dbd1efe6976e748a2d72df10775a4524

A breaking change should be reported for AUViewController, it's expected, the method was moved to the parent, nothing's broken (:

-----

Also I went for the option of inlining the protocol members that weren’t there already. 

e.g: https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c#file-diff-L638-L677
and https://gist.github.com/VincentDondain/36cd2ca79628bb4b07a5145e46f0150c#file-diff-L146-L164

**Comment by VincentDondain** [comment]
> Xamarin.iOS.Tasks.TargetTests.RebuildExecutable_NoModifications: #1: ../MySingleView/bin/iPhoneSimulator/Debug/MySingleView.app/MySingleView Expected: 2018-01-13 00:15:29.000 But was: 2018-01-13 00:15:30.000

Known issue https://github.com/xamarin/maccore/issues/592

File: src/gamekit.cs [hunk 14]
```diff
@@ -855,13 +859,14 @@ interface GKSavedGame : NSCopying {
...
 	[NoWatch]
-	[NoTV]
 	[Protocol, Model]
 	[BaseType (typeof (NSObject))]
 	interface GKSavedGameListener {
+		[NoTV]
 		[Export ("player:didModifySavedGame:")]
 		void DidModifySavedGame (GKPlayer player, GKSavedGame savedGame);
 
+		[NoTV]
```
Comment (spouliot) [inline src/gamekit.cs]: Let me go back one step (I might have induced you into an error earlier)

This looks like the protocol does not really exists in tvOS and that Apple just annotated the members and not the type itself. In doubt let's open a radar and add a comment/link into the xtro data

File: src/webkit.cs [hunk 15]
```diff
@@ -2426,7 +2426,11 @@ partial interface WebScriptObject {
 			   "WeakUIDelegate",
 			   "WeakPolicyDelegate" }
 		   )]
-	partial interface WebView {
+	partial interface WebView
+#if MONOMAC
+		: NSUserInterfaceValidations
+#endif
+{
```
Comment (spouliot) [inline src/webkit.cs]: minor: indent

File: src/wkwebkit.cs [hunk 16]
```diff
@@ -539,7 +539,11 @@ interface WKUserScript : NSCopying {
 #endif
 	)]
 	[DisableDefaultCtor ()] // Crashes during deallocation in Xcode 6 beta 2. radar 17377712.
-	interface WKWebView {
+	interface WKWebView
+#if MONOMAC
+		: NSUserInterfaceValidations
+#endif
+{
```
Comment (spouliot) [inline src/wkwebkit.cs]: minor: indent

File: tests/introspection/ApiSelectorTest.cs [hunk 17]
```diff
@@ -175,6 +175,19 @@ protected virtual bool Skip (Type type, string selectorName)
 					return !TestRuntime.CheckXcodeVersion (9, 0);
 				}
 				break;
+			case "NSUrl":
+				switch (selectorName) {
+				case "previewItemTitle":
+					// 'previewItemTitle' should be optional (fixed in XAMCORE_4_0)
+					return true;
+				}
+				break;
```
Comment (spouliot) [inline tests/introspection/ApiSelectorTest.cs]: minor: that block could have been inside a `#if !XAMCORE_4_0`

File: tests/xtro-sharpie/tvOS-GameKit.ignore [hunk 18]
```diff
@@ -7,7 +7,6 @@
 ## all members are not available so the protocol is empty
 ## however this is confusing because some protocols have no members (so it can't just be ignored)
 !missing-protocol! GKFriendRequestComposeViewControllerDelegate not bound
-!missing-protocol! GKSavedGameListener not bound
```
Comment (spouliot) [inline tests/xtro-sharpie/tvOS-GameKit.ignore]: see comment above

File: src/gamekit.cs (hunk 14 above)
Comment (VincentDondain) [reply src/gamekit.cs]: Yea this is confusing.

Also one comment in xtro said:

```
## all members are not available so the protocol is empty
## however this is confusing because some protocols have no members (so it can't just be ignored)
```

I was thinking they added the conformance (even if the protocol is empty on tvOS) for later.

But yea I can also revert that, open a radar and annotate xtro.

Comment (spouliot) [reply src/gamekit.cs]: it's tricky since exposing the protocol (if not supported) could be considered a private API (when apps are analyzed) on tvOS. Since I don't see any benefit from an empty protocol then let's play it safe :)

File: src/coreaudiokit.cs [hunk 19]
```diff
@@ -28,7 +28,7 @@ namespace XamCore.CoreAudioKit {
 #if XAMCORE_2_0 || !MONOMAC
 	[iOS (9,0)][Mac (10,11, onlyOn64 : true)]
 	[BaseType (typeof(AUViewControllerBase))]
-	interface AUViewController : NSExtensionRequestHandling {
+	interface AUViewController {
```
Comment (rolfbjarne) [inline src/coreaudiokit.cs]: @VincentDondain: This is a breaking change:

screenshot 2018-01-29 10 39 14

Comment (VincentDondain) [reply src/coreaudiokit.cs]: @rolfbjarne It's `UIViewController` that implements `NSExtensionRequestHandling` now (as part of [this PR](https://github.com/xamarin/xamarin-macios/pull/3187/files#diff-1ca9e8e46629c0f8806cee2c8be4aad3R13599)).

Then based on https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#types:

**Allowed**
> Removing an interface implementation from a type when the interface is already implemented lower in the hierarchy

Comment (VincentDondain) [reply src/coreaudiokit.cs]: Also I asked about this exact case and you answered me :P

https://xamarinhq.slack.com/archives/C03CCJNR7/p1515786537000437

Vincent:

> I’m getting a breaking change from API diff but I don’t understand how come it’s a breaking change
> I move a protocol from a subclass to its parent. So the generated method from the protocol is removed from the subclass (that’s what’s reported as a breaking change) but that method is now on the base class…
> so even if a subclass of a subclass was overriding that virtual method, it should still be fine
> https://gist.github.com/VincentDondain/dbd1efe6976e748a2d72df10775a4524#file-new-diff-L189-L213 and https://gist.github.com/VincentDondain/dbd1efe6976e748a2d72df10775a4524#file-new-diff-L599-L623

Rolf:

> You’re assuming apidiff is infallible :slightly_smiling_face:
> Moving members to a base class is one case where it will say it’s a breaking change when it isn’t

Comment (rolfbjarne) [reply src/coreaudiokit.cs]: @VincentDondain heh, ok, hopefully I'll remember the next time I run into this :smile: 👍
