### PR TITLE
Add MonoTouch support for Dedup

### PR DESCRIPTION
**Pull request by alexanderkyte**
This is set by altering ` msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props` to contain ```<MtouchEnableDedup Condition="'$(MtouchEnableDedup)' ==''">True</MtouchEnableDedup>```

https://github.com/mono/mono/issues/7049

### CODE REVIEW

File: tools/mtouch/Target.cs [hunk 1]
```diff
@@ -802,9 +813,31 @@ public void ProcessAssemblies ()
...
+			var dedupDummyDll = String.Format ("{0}.dll", DedupDummyName);
+			// Make available for the AOT compiler
+			var dllPath = Path.Combine (BuildDirectory, dedupDummyDll);
+
+			// Qualified because of collisions with cecil
+			var aName = new System.Reflection.AssemblyName (DedupDummyName);
+			var ab = AppDomain.CurrentDomain.DefineDynamicAssembly (aName, System.Reflection.Emit.AssemblyBuilderAccess.RunAndSave, BuildDirectory);
+
+			// Make .dll file
+			ab.Save (dedupDummyDll);
```
Comment (rolfbjarne) [inline tools/mtouch/Target.cs]: Is the dedup assembly needed at runtime? Or only at build time?

File: tools/mtouch/BuildTasks.mtouch.cs [hunk 2]
```diff
@@ -191,36 +191,57 @@ public class AOTTask : ProcessTask
...
-					var mdb = Assembly.FullPath + ".mdb";
-					if (File.Exists (mdb))
-						inputs.Add (mdb);
-					var pdb = Path.ChangeExtension (Assembly.FullPath, ".pdb");
-					if (File.Exists (pdb))
-						inputs.Add (pdb);
-					var config = Assembly.FullPath + ".config";
-					if (File.Exists (config))
-						inputs.Add (config);
+					foreach (var ass_dep in InputAssemblies) {
```
Comment (chamons) [inline tools/mtouch/BuildTasks.mtouch.cs]: Rename variable

File: tools/mtouch/Target.cs (hunk 1 above)
Comment (spouliot) [reply tools/mtouch/Target.cs]: it's a constant, empty assembly being created each time right ?
maybe we can embed one (pre-created) and extract it when needed (saving build time)

File: msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs [hunk 3]
```diff
@@ -106,6 +106,9 @@ public GccOptions ()
 		[Required]
 		public bool EnableSGenConc { get; set; }
 
+		[Required]
+		public bool EnableDedup { get; set; }
+
```
[the remark this answers is not in the document]
Comment (alexanderkyte) [reply msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs]: How would you like to get numbers? @spouliot

File: tools/common/Target.cs [hunk 4]
```diff
@@ -44,6 +44,8 @@ public partial class Target {
 		public HashSet<string> Frameworks = new HashSet<string> ();
 		public HashSet<string> WeakFrameworks = new HashSet<string> ();
 
+		public const string DedupDummyName = "DedupDummy";
```
[the remark this answers is not in the document]
Comment (alexanderkyte) [reply tools/common/Target.cs]: Would you prefer the name "Mock" or maybe "Container"?

File: tools/mtouch/Assembly.cs [hunk 5]
```diff
@@ -270,7 +276,18 @@ public void CreateAOTTask (Abi abi)
 			aotInfo.AotDataFiles.Add (data);
 
 			var aotCompiler = Driver.GetAotCompiler (App, Target.Is64Build);
-			var aotArgs = Driver.GetAotArguments (App, assembly_path, abi, build_dir, asm_output, llvm_aot_ofile, data);
+			var aotOpts = Driver.GetAotOptions (App, assembly_path, abi, build_dir, asm_output, llvm_aot_ofile, data, IsDedupDummy);
+
+			if (IsDedupDummy) {
+				// Includes this Assembly
+				foreach (var assm in Target.Assemblies)
+					aotOpts.Append (" \"").Append (assm.FullPath).Append ("\"");
```
[the remark this answers is not in the document]
Comment (alexanderkyte) [reply tools/mtouch/Assembly.cs]: I'm not sure I follow. When you AOT the dedup dummy you have to pass every assembly being AOT'ed to mono.

File: tools/mtouch/BuildTasks.mtouch.cs [hunk 6]
```diff
@@ -191,36 +191,57 @@ public class AOTTask : ProcessTask
...
+					}
 				}
 				return inputs;
 			}
 		}
 
 		public override bool IsUptodate {
 			get {
+				if (Assembly.IsDedupDummy)
+					return false;
```
[the remark this answers is not in the document]
Comment (alexanderkyte) [reply tools/mtouch/BuildTasks.mtouch.cs]: Strictly speaking, the contents of the dedup dummy amodule will end up having to be recompiled every time that any other assembly changes. I could make this case depend on the IsUptodate property of every other assembly provided.

[the remark this answers is not in the document]
Comment (alexanderkyte) [reply tools/mtouch/BuildTasks.mtouch.cs]: Can I force this to always be rebuilt if we rebuild, but not trigger a rebuild?

File: tools/mtouch/Target.cs (hunk 1 above)
Comment (rolfbjarne) [reply tools/mtouch/Target.cs]: We can probably just install it in /Library/Frameworks/Xamarin.iOS.framework and build it directly from there.

One point here is that using reflection like this will reference the desktop profile (v4.5 mscorlib) instead of the correct profile.

Comment (spouliot) [reply tools/mtouch/Target.cs]: @rolfbjarne not sure I follow wrt reflection. This looked like an empty assembly where dedup'ed code is moved (shared) later

File: tools/common/Target.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (spouliot) [reply tools/common/Target.cs]: open to suggestion, but ideally something more obvious that people won't ask back "what is it" ? :)
maybe `Xamarin.DeduplicatedAotCode` ?

File: tools/mtouch/BuildTasks.mtouch.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (spouliot) [reply tools/mtouch/BuildTasks.mtouch.cs]: @rolfbjarne any suggestion ?

File: msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (spouliot) [reply msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs]: We track the size of several applications across releases, so I can use a package including the PR and see how much is saved. The build times for them are not very precise but @rolfbjarne is working on something better to track them.

File: tools/mtouch/BuildTasks.mtouch.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (rolfbjarne) [reply tools/mtouch/BuildTasks.mtouch.cs]: The best way to do this depends on whether the dedup assembly is needed at runtime or not, which I already asked here: https://github.com/xamarin/xamarin-macios/pull/3783#discussion_r175665845

[the remark this answers is not in the document]
Comment (alexanderkyte) [reply tools/mtouch/BuildTasks.mtouch.cs]: It’s very necessary, as loading it at runtime loads all of the deduplicated inflated methods and wrappers. It is a container for all AOT code that does not have a 1-1 mapping with a managed method.

[the remark this answers is not in the document]
Comment (spouliot) [reply tools/mtouch/BuildTasks.mtouch.cs]: I think @rolfbjarne meant the metadata, not the AOT code from that assembly (which ends up in the native executable). My guess is that it's needed, along with the .aotdata file, but my understanding of it could be wrong :)

[the remark this answers is not in the document]
Comment (rolfbjarne) [reply tools/mtouch/BuildTasks.mtouch.cs]: Ah, I guess the aotdata is needed, because the assembly itself contains nothing interesting, and the native code ends up in the executable.

File: tools/mtouch/BuildTasks.mtouch.cs [hunk 7]
```diff
@@ -191,36 +191,57 @@ public class AOTTask : ProcessTask
...
-						inputs.Add (mdb);
-					var pdb = Path.ChangeExtension (Assembly.FullPath, ".pdb");
-					if (File.Exists (pdb))
-						inputs.Add (pdb);
-					var config = Assembly.FullPath + ".config";
-					if (File.Exists (config))
-						inputs.Add (config);
+					foreach (var asm_dep in InputAssemblies) {
+						if (asm_dep.HasDependencyMap)
+							inputs.AddRange (asm_dep.DependencyMap);
```
Comment (rolfbjarne) [inline tools/mtouch/BuildTasks.mtouch.cs]: `inputs` should probably be made a `HashSet<string>` now, since otherwise it can end up with multiple identical paths (it's probably not directly wrong, just wasteful).

File: tools/mtouch/BuildTasks.mtouch.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (rolfbjarne) [reply tools/mtouch/BuildTasks.mtouch.cs]: This should not be needed as long as `FileDependencies` list all the assemblies when AOT-compiling the dedup assembly (which it looks like it does).

File: tools/mtouch/Target.cs [hunk 8]
```diff
@@ -622,19 +622,32 @@ public void ManagedLink ()
 					                               $"The linker output contains more than one assemblies named '{group.Key}':\n\t{string.Join ("\n\t", group.Select ((v) => v.MainModule.FileName).ToArray ())}");
 			}
 
+			Assembly dummy = null;
+			if (App.EnableDedup) {
+				foreach (var a in Assemblies)
+					if (a.IsDedupDummy)
+						dummy = a;
```
Comment (rolfbjarne) [inline tools/mtouch/Target.cs]: You can break out of the foreach once you've found the assembly.

File: tools/mtouch/Target.cs [hunk 9]
```diff
@@ -622,19 +622,32 @@ public void ManagedLink ()
...
+			}
+
 			// Update (add/remove) list of assemblies in each app, since the linker may have both added and removed assemblies.
 			// The logic for updating assemblies when doing code-sharing is not equivalent to when we're not code sharing
 			// (in particular code sharing is not supported when there are xml linker definitions), so we need
 			// to maintain two paths here.
 			if (sharingTargets.Count == 0) {
 				Assemblies.Update (this, output_assemblies);
+				if (dummy != null)
```
Comment (rolfbjarne) [inline tools/mtouch/Target.cs]: What happens if you add `dummy` to `output_assemblies` a few lines above (so that you don't duplicate logic here and below)?

Comment (alexanderkyte) [reply tools/mtouch/Target.cs]: That would prevent the duplication here but output_assemblies aren't added to each target in the lower portion

**Comment by alexanderkyte** [comment]
failure due to https://github.com/xamarin/xamarin-macios/pull/3799

**Comment by spouliot** [comment]
@alexanderkyte the PR is **not** the reason for the failure, it just report things

The failure is just a few lines above in the logs, i.e.
```
04:26:33 BuildTasks.mtouch.cs(222,32): error CS0230: Type and identifier are both required in a foreach statement
04:26:33 
make[3]: *** [bin/Makefile/mtouch.exe] Error 1
04:26:33 make[2]: *** [all-recurse] Error 1
04:26:33 make[1]: *** [all-recurse] Error 1
04:26:33 make: *** [world] Error 2
04:26:33 Build step 'Execute shell' marked build as failure
```

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
@alexanderkyte I've added a new dedup test, which shows that the `link sdk` or `link all` fail AOT compilation if deduplication is enabled:

```
AOT Compilation exited with code 139, command:
MONO_PATH=/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.MTouch.Dedup/2/link sdk/obj/iPhone/Debug64-unified/mtouch-cache/3-Build /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile='/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.MTouch.Dedup/2/link sdk/obj/iPhone/Debug64-unified/mtouch-cache/arm64/System.Xml.aotdata.arm64',static,asmonly,direct-icalls,full,dwarfdebug,no-direct-calls,direct-pinvoke,dedup-skip,outfile='/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.MTouch.Dedup/2/link sdk/obj/iPhone/Debug64-unified/mtouch-cache/arm64/System.Xml.dll.s' '/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/mtouch/bin/Debug/tmp-test-dir/Xamarin.MTouch.Dedup/2/link sdk/obj/iPhone/Debug64-unified/mtouch-cache/3-Build/System.Xml.dll'
```

To repro, run this from the xamarin-macios directory:

```shell
msbuild /p:Platform=iPhone /p:MtouchEnableDedup=True /p:Configuration=Debug64 "tests/linker/ios/link sdk/link sdk.csproj"
```

**Comment by rolfbjarne** [comment]
This is almost 3 years old, and the PR has bitrotted quite much, so I'm closing this. We can always resurrect it if we decide to spend more time on dedup again in the future.
