### PR TITLE
[mmp] Set minimum Xcode to Xcode 12 to get a better error message. Fixes #11937.

### LINKED ISSUE #11937: Xamarin.Mac: MM5309 error when using Xcode earlier than Xcode 12
### Steps to Reproduce

1. Create a new Xamarin.Mac project
2. Build with Xcode 11

Native linking failure with Xcode 11.3.1

```
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _ves_icall_System_ConsoleDriver_InternalKeyAvailable in libmonosgen-2.0.a(libmonoruntimesgen_la-console-unix.o)
      _socket_transport_connect in libmonosgen-2.0.a(libmono_dbg_la-debugger-agent.o)
      _monoeg_g_spawn_command_line_sync in libmonosgen-2.0.a(libeglib_la-gspawn.o)
      _mono_poll in libmonosgen-2.0.a(libmonoutils_la-mono-poll.o)
  "_pthread_jit_write_protect_np", referenced from:
      _free_chunklist in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _new_codechunk in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _mono_codeman_enable_write in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _mono_codeman_disable_write in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _codechunk_valloc in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.
```

Native linking failure with Xcode 11.7

```
Undefined symbols for architecture x86_64:
  "_pthread_jit_write_protect_np", referenced from:
      _free_chunklist in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _new_codechunk in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _mono_codeman_enable_write in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _mono_codeman_disable_write in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
      _codechunk_valloc in libmonosgen-2.0.a(libmonoutils_la-mono-codeman.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.


```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Developers will now get the helpful:

> error MM0051: Xamarin.Mac 7.99.0 requires Xcode 12.0 or later. The current Xcode version (found in /Applications/Xcode_11.7.app/Contents/Developer) is 11.7.

instead of:

> error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.

(and no clue from the build log that they need to upgrade their Xcode).

Xamarin.iOS projects still build fine with at least Xcode 11.3.1, so I've only
updated the minimum Xcode version for Xamarin.Mac.

Fixes https://github.com/xamarin/xamarin-macios/issues/11937.

### CODE REVIEW

**Review by spouliot — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* monotouch-test/tvOS - simulator/Debug: https://github.com/xamarin/maccore/issues/1605
* introspection/watchOS 32-bits - simulator/Debug (watchOS 5.0): https://github.com/xamarin/maccore/issues/2454
